import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { isValidUuid } from "@/lib/patients/validation";
import { formatClinicDate } from "@/lib/agenda/dates";
import { listStockMovements } from "@/lib/stock/queries";
import { isStockMovementType, movementLabels } from "@/lib/stock/validation";
import type { StockMovementType } from "@/lib/stock/types";

type SearchParams = Promise<{ material?: string | string[]; tipo?: string | string[]; inicio?: string | string[]; fim?: string | string[]; page?: string | string[] }>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
function href(values: { material?: string; type?: StockMovementType; start?: string; end?: string; page?: number }) { const p = new URLSearchParams(); if (values.material) p.set("material", values.material); if (values.type) p.set("tipo", values.type); if (values.start) p.set("inicio", values.start); if (values.end) p.set("fim", values.end); if ((values.page ?? 1) > 1) p.set("page", String(values.page)); return `/estoque/movimentacoes${p.size ? `?${p}` : ""}`; }

export default async function StockMovementsPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser(); const params = await searchParams; const material = first(params.material); const materialId = material && isValidUuid(material) ? material : undefined; const rawType = first(params.tipo); const type = rawType && isStockMovementType(rawType) ? rawType : undefined; const start = first(params.inicio); const end = first(params.fim); const number = Number(first(params.page) ?? "1"); const page = Number.isSafeInteger(number) && number > 0 ? number : 1;
  const result = await listStockMovements({ materialId, type, startDate: start, endDate: end, page }); const totalPages = Math.max(1, Math.ceil(result.total / result.pageSize));
  return <div className="mx-auto max-w-7xl space-y-5"><Link href="/estoque" className="text-sm text-muted-foreground hover:text-foreground">← Voltar para estoque</Link><header><h2 className="text-2xl font-medium">Movimentações de estoque</h2><p className="mt-1 text-sm text-muted-foreground">{user.perfil === "dentista" ? "Visualize apenas os consumos registrados por você." : "Histórico operacional completo, sem exclusão física."}</p></header><form className="grid gap-2 rounded-xl border border-border bg-card p-3 md:grid-cols-4"><select name="tipo" defaultValue={type ?? ""} className="h-10 rounded-md border border-border bg-input-background px-3 text-sm"><option value="">Todos os tipos</option>{(["entrada", "saida", "ajuste"] as StockMovementType[]).map((item) => <option key={item} value={item}>{movementLabels[item]}</option>)}</select><input name="inicio" type="date" defaultValue={start} className="h-10 rounded-md border border-border bg-input-background px-3 text-sm"/><input name="fim" type="date" defaultValue={end} className="h-10 rounded-md border border-border bg-input-background px-3 text-sm"/><button className="h-10 rounded-md border border-border px-3 text-sm font-medium hover:bg-secondary">Filtrar</button>{materialId && <input type="hidden" name="material" value={materialId} />}</form>{result.movements.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">Nenhuma movimentação visível para os filtros selecionados.</div> : <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="hidden grid-cols-[1fr_1.2fr_.75fr_.75fr_1fr_1.4fr] gap-3 border-b border-border px-4 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground md:grid"><span>Data</span><span>Material</span><span>Tipo</span><span>Saldo</span><span>Usuário</span><span>Motivo</span></div><div className="divide-y divide-border">{result.movements.map((movement) => <article key={movement.id} className="grid gap-1 px-4 py-4 text-sm md:grid-cols-[1fr_1.2fr_.75fr_.75fr_1fr_1.4fr] md:items-center md:gap-3"><span>{formatClinicDate(movement.created_at,{dateStyle:"short",timeStyle:"short"})}</span><span className="font-medium">{movement.material_nome}</span><span>{movementLabels[movement.tipo]} · {movement.quantidade}</span><span>{movement.quantidade_anterior} → {movement.quantidade_posterior}</span><span className="text-muted-foreground">{movement.usuario_nome}</span><span className="text-muted-foreground">{movement.motivo ?? movement.referencia ?? "—"}</span></article>)}</div></section>}{result.total > result.pageSize && <nav className="flex justify-end gap-2 text-sm">{page > 1 && <Link href={href({ material: materialId, type, start, end, page: page - 1 })} className="rounded border px-3 py-1.5">Anterior</Link>}{page < totalPages && <Link href={href({ material: materialId, type, start, end, page: page + 1 })} className="rounded border px-3 py-1.5">Próxima</Link>}</nav>}</div>;
}
