import Link from "next/link";
import { AlertTriangle, Archive, Plus, TriangleAlert } from "lucide-react";
import { requireUser } from "@/lib/auth/session";
import { getStockSummary, listStockMaterials } from "@/lib/stock/queries";
import { isStockStatus, unitLabels } from "@/lib/stock/validation";
import type { StockStatus } from "@/lib/stock/types";

type SearchParams = Promise<{ q?: string | string[]; categoria?: string | string[]; status?: string | string[]; page?: string | string[] }>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const statusLabels: Record<StockStatus, string> = { normal: "Normal", estoque_baixo: "Estoque baixo", vencendo: "Vencendo", vencido: "Vencido", inativo: "Inativo" };
const statusTone: Record<StockStatus, string> = { normal: "bg-slate-100 text-slate-700", estoque_baixo: "bg-amber-50 text-amber-800", vencendo: "bg-orange-50 text-orange-800", vencido: "bg-red-50 text-red-700", inativo: "bg-slate-200 text-slate-600" };

function href(values: { q?: string; categoria?: string; status?: StockStatus; page?: number }) { const params = new URLSearchParams(); if (values.q) params.set("q", values.q); if (values.categoria) params.set("categoria", values.categoria); if (values.status) params.set("status", values.status); if ((values.page ?? 1) > 1) params.set("page", String(values.page)); const query = params.toString(); return query ? `/estoque?${query}` : "/estoque"; }

export default async function StockPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser(); const params = await searchParams; const query = (first(params.q) ?? "").trim().slice(0, 100); const category = (first(params.categoria) ?? "").trim().slice(0, 100); const rawStatus = first(params.status); const status = rawStatus && isStockStatus(rawStatus) ? rawStatus : undefined; const requestedPage = Number(first(params.page) ?? "1"); const page = Number.isSafeInteger(requestedPage) && requestedPage > 0 ? requestedPage : 1;
  const [result, summary] = await Promise.all([listStockMaterials({ query, category, status, page }), user.perfil === "dentista" ? Promise.resolve(null) : getStockSummary()]);
  const totalPages = Math.max(1, Math.ceil(result.total / result.pageSize));
  return <div className="mx-auto max-w-7xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-medium">Estoque</h2><p className="mt-1 text-sm text-muted-foreground">Controle de materiais da clínica.</p></div><div className="flex gap-2"><Link href="/estoque/movimentacoes" className="inline-flex h-9 items-center rounded-md border border-border px-3 text-sm font-medium hover:bg-secondary">Movimentações</Link>{user.perfil === "administrador" && <Link href="/estoque/novo" className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90"><Plus className="h-4 w-4" />Novo material</Link>}</div></header>
    {summary && <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumo do estoque"><Metric label="Materiais ativos" value={summary.total_ativos} icon={Archive} /><Metric label="Estoque baixo" value={summary.estoque_baixo} icon={TriangleAlert} tone="text-amber-600" /><Metric label="Vencendo em 30 dias" value={summary.vencendo} icon={AlertTriangle} tone="text-orange-600" /><Metric label="Vencidos" value={summary.vencidos} icon={AlertTriangle} tone="text-red-600" /></section>}
    <form className="grid gap-2 rounded-xl border border-border bg-card p-3 md:grid-cols-[1.5fr_1fr_1fr_auto]"><input name="q" defaultValue={query} placeholder="Buscar material" className="h-10 rounded-md border border-border bg-input-background px-3 text-sm" /><input name="categoria" defaultValue={category} placeholder="Categoria" className="h-10 rounded-md border border-border bg-input-background px-3 text-sm" /><select name="status" defaultValue={status ?? ""} className="h-10 rounded-md border border-border bg-input-background px-3 text-sm"><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="h-10 rounded-md border border-border px-4 text-sm font-medium hover:bg-secondary">Filtrar</button></form>
    {result.materials.length === 0 ? <section className="rounded-xl border border-dashed border-border p-10 text-center"><Archive className="mx-auto h-8 w-8 text-muted-foreground" /><h3 className="mt-3 font-medium">Nenhum material encontrado.</h3><p className="mt-1 text-sm text-muted-foreground">Ajuste os filtros ou cadastre o primeiro material.</p>{user.perfil === "administrador" && <Link href="/estoque/novo" className="mt-4 inline-flex h-9 items-center rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Cadastrar material</Link>}</section> : <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="hidden grid-cols-[1.3fr_1fr_.65fr_.65fr_.8fr_1fr_1.3fr] gap-3 border-b border-border px-4 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground md:grid"><span>Material</span><span>Categoria</span><span>Quantidade</span><span>Mínimo</span><span>Validade</span><span>Fornecedor</span><span>Status</span></div><div className="divide-y divide-border">{result.materials.map((material) => <Link key={material.id} href={`/estoque/${material.id}`} className="grid gap-1 px-4 py-4 hover:bg-secondary/50 md:grid-cols-[1.3fr_1fr_.65fr_.65fr_.8fr_1fr_1.3fr] md:items-center md:gap-3"><span className="font-medium">{material.nome}<span className="ml-1 text-xs font-normal text-muted-foreground">· {unitLabels[material.unidade]}</span></span><span className="text-sm text-muted-foreground">{material.categoria}</span><span className="text-sm">{material.quantidade_atual}</span><span className="text-sm">{material.estoque_minimo}</span><span className="text-sm text-muted-foreground">{material.validade ?? "—"}</span><span className="truncate text-sm text-muted-foreground">{material.fornecedor ?? "—"}</span><span className="flex flex-wrap gap-1">{!material.ativo ? <StatusBadge status="inativo" /> : <>{material.estoque_baixo && <StatusBadge status="estoque_baixo" />}{material.vencendo && <StatusBadge status="vencendo" />}{material.vencido && <StatusBadge status="vencido" />}{!material.estoque_baixo && !material.vencendo && !material.vencido && <StatusBadge status="normal" />}</>}</span></Link>)}</div></section>}
    {result.total > result.pageSize && <nav className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Página {page} de {totalPages} · {result.total} materiais</span><div className="flex gap-2">{page > 1 && <Link href={href({ q: query, categoria: category, status, page: page - 1 })} className="rounded-md border border-border px-3 py-1.5">Anterior</Link>}{page < totalPages && <Link href={href({ q: query, categoria: category, status, page: page + 1 })} className="rounded-md border border-border px-3 py-1.5">Próxima</Link>}</div></nav>}</div>;
}

function Metric({ label, value, icon: Icon, tone = "text-primary" }: { label: string; value: number; icon: typeof Archive; tone?: string }) { return <article className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">{label}</p><Icon className={`h-4 w-4 ${tone}`} /></div><p className="mt-2 text-2xl font-semibold">{value}</p></article>; }
function StatusBadge({ status }: { status: StockStatus }) { return <span className={`inline-flex rounded px-2 py-1 text-xs font-medium ${statusTone[status]}`}>{statusLabels[status]}</span>; }
