"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/session";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { DomainActionState, TaskStatus } from "@/lib/operational/types";
const result=(error:string|null):DomainActionState=>({success:!error,error});
export async function createTask(_:DomainActionState,form:FormData):Promise<DomainActionState>{await requireUser();const s=await createSupabaseServerClient();const {error}=await s.rpc("create_task",{p_titulo:String(form.get("title")??""),p_descricao:String(form.get("description")??"")||null,p_prazo:String(form.get("dueDate")??"")||null,p_responsavel_id:String(form.get("assigneeId")??""),p_paciente_id:String(form.get("patientId")??"")||null,p_agendamento_id:null});if(error)return result("Não foi possível criar a tarefa.");revalidatePath("/tarefas");return result(null)}
export async function setTaskStatus(_:DomainActionState,form:FormData):Promise<DomainActionState>{await requireUser();const status=String(form.get("status")??"")as TaskStatus;if(status!=="concluida"&&status!=="cancelada")return result("Status inválido.");const s=await createSupabaseServerClient();const {error}=await s.rpc("set_task_status",{p_tarefa_id:String(form.get("taskId")??""),p_status:status});if(error)return result("Não foi possível atualizar a tarefa.");revalidatePath("/tarefas");return result(null)}
export async function updateTask(_:DomainActionState,form:FormData):Promise<DomainActionState>{await requireUser();const s=await createSupabaseServerClient();const {error}=await s.rpc("update_task",{p_tarefa_id:String(form.get("taskId")??""),p_titulo:String(form.get("title")??""),p_descricao:String(form.get("description")??"")||null,p_prazo:String(form.get("dueDate")??"")||null,p_responsavel_id:String(form.get("assigneeId")??""),p_paciente_id:null,p_agendamento_id:null});if(error)return result("Não foi possível editar a tarefa.");revalidatePath("/tarefas");return result(null)}
