"use client";

import Link from "next/link";
import { useActionState } from "react";
import { CheckCircle2, CircleDashed, ClipboardCheck, Pencil, Plus, UserRound, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { initialDomainActionState } from "@/lib/agenda/action-state";
import { formatClinicDate } from "@/lib/agenda/dates";
import type { OperationalTask, TaskStatus } from "@/lib/operational/types";
import { createTask, setTaskStatus, updateTask } from "./actions";

type Assignee = { id: string; nome: string; perfil: string };

const STATUS: Record<TaskStatus, { label: string; tone: "info" | "success" | "danger" }> = {
  pendente: { label: "Pendente", tone: "info" },
  concluida: { label: "Concluída", tone: "success" },
  cancelada: { label: "Cancelada", tone: "danger" },
};

function SummaryCard({ label, value, description, icon: Icon, tone = "text-primary" }: { label: string; value: string | number; description: string; icon: typeof CircleDashed; tone?: string }) {
  return <div className="rounded-lg border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold text-foreground">{value}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><Icon className={`h-5 w-5 ${tone}`} /></div></div>;
}

function TaskCreationForm({ assignees, currentUserId }: { assignees: Assignee[]; currentUserId: string }) {
  const [state, action, pending] = useActionState(createTask, initialDomainActionState);
  return <form action={action} className="border-t border-border px-5 py-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="lg:col-span-2"><span className="mb-1 block text-xs font-medium text-foreground">Título</span><input name="title" required minLength={2} maxLength={200} placeholder="Ex.: Confirmar retorno" className="h-10 w-full rounded-md border border-border bg-input-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs font-medium text-foreground">Prazo</span><input name="dueDate" type="date" className="h-10 w-full rounded-md border border-border bg-input-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs font-medium text-foreground">Responsável</span><select name="assigneeId" defaultValue={currentUserId} className="h-10 w-full rounded-md border border-border bg-input-background px-3 text-sm">{assignees.map((assignee) => <option key={assignee.id} value={assignee.id}>{assignee.nome}</option>)}</select></label><label className="sm:col-span-2 lg:col-span-4"><span className="mb-1 block text-xs font-medium text-foreground">Descrição</span><textarea name="description" maxLength={2000} rows={2} placeholder="Informação operacional opcional" className="w-full resize-y rounded-md border border-border bg-input-background px-3 py-2 text-sm" /></label></div><div className="mt-4 flex items-center gap-3"><button disabled={pending} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"><Plus className="h-4 w-4" />{pending ? "Salvando..." : "Criar tarefa"}</button>{state.error && <p role="alert" className="text-sm text-destructive">{state.error}</p>}</div></form>;
}

function TaskActions({ task, assignees, canEdit }: { task: OperationalTask; assignees: Assignee[]; canEdit: boolean }) {
  const [statusState, statusAction, changingStatus] = useActionState(setTaskStatus, initialDomainActionState);
  const [editState, editAction, editing] = useActionState(updateTask, initialDomainActionState);
  if (task.status !== "pendente") return null;

  return <div className="flex flex-wrap items-center gap-2"><form action={statusAction} className="contents"><input type="hidden" name="taskId" value={task.id} /><button name="status" value="concluida" disabled={changingStatus} className="inline-flex h-8 items-center gap-1 rounded-md border border-emerald-200 bg-emerald-50 px-2.5 text-xs font-medium text-emerald-700 hover:bg-emerald-100 disabled:opacity-50"><CheckCircle2 className="h-3.5 w-3.5" /> Concluir</button><button name="status" value="cancelada" disabled={changingStatus} className="inline-flex h-8 items-center rounded-md px-2.5 text-xs font-medium text-muted-foreground hover:bg-secondary disabled:opacity-50">Cancelar</button></form>{canEdit && <details className="relative"><summary className="inline-flex h-8 cursor-pointer list-none items-center gap-1 rounded-md border border-border bg-card px-2.5 text-xs font-medium text-primary hover:bg-accent"><Pencil className="h-3.5 w-3.5" /> Editar</summary><form action={editAction} className="absolute right-0 z-20 mt-2 grid w-[min(22rem,calc(100vw-3rem))] gap-2 rounded-lg border border-border bg-card p-3 shadow-xl"><input type="hidden" name="taskId" value={task.id} /><input name="title" defaultValue={task.titulo} required minLength={2} maxLength={200} aria-label="Título da tarefa" className="h-9 rounded-md border border-border px-2 text-sm" /><input name="dueDate" type="date" defaultValue={task.prazo ?? ""} aria-label="Prazo" className="h-9 rounded-md border border-border px-2 text-sm" /><select name="assigneeId" defaultValue={task.responsavel_id} aria-label="Responsável" className="h-9 rounded-md border border-border px-2 text-sm">{assignees.map((assignee) => <option key={assignee.id} value={assignee.id}>{assignee.nome}</option>)}</select><textarea name="description" defaultValue={task.descricao ?? ""} maxLength={2000} aria-label="Descrição" rows={2} className="rounded-md border border-border px-2 py-1.5 text-sm" /><button disabled={editing} className="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground disabled:opacity-50">{editing ? "Salvando..." : "Salvar edição"}</button>{editState.error && <p role="alert" className="text-xs text-destructive">{editState.error}</p>}</form></details>}{statusState.error && <p role="alert" className="w-full text-xs text-destructive">{statusState.error}</p>}</div>;
}

function TaskTitle({ task }: { task: OperationalTask }) {
  const completed = task.status === "concluida";
  return <div className="flex min-w-0 items-start gap-2"><CheckCircle2 className={`mt-0.5 h-4 w-4 shrink-0 ${completed ? "text-emerald-600" : "text-muted-foreground/50"}`} /><div className="min-w-0"><p className={`font-medium text-foreground ${completed ? "line-through text-muted-foreground" : ""}`}>{task.titulo}</p>{task.descricao && <p className={`mt-0.5 line-clamp-1 text-xs text-muted-foreground ${completed ? "line-through" : ""}`}>{task.descricao}</p>}</div></div>;
}

function TaskRows({ tasks, assignees, currentUserId, profile }: { tasks: OperationalTask[]; assignees: Assignee[]; currentUserId: string; profile: string }) {
  return <>{tasks.map((task) => { const canEdit = profile === "administrador" || profile === "recepcao" || task.created_by === currentUserId; const status = STATUS[task.status]; return <div key={task.id} className="contents"><div className="hidden border-b border-border last:border-b-0 md:table-row"><div className="px-4 py-4 align-top"><TaskTitle task={task} /></div><div className="px-4 py-4 align-top text-sm text-foreground">{task.responsavel_nome}</div><div className="px-4 py-4 align-top text-sm text-muted-foreground">{task.prazo ? formatClinicDate(task.prazo, { day: "2-digit", month: "short", year: "numeric" }) : "Sem prazo"}</div><div className="px-4 py-4 align-top text-sm">{task.paciente_id && task.paciente_nome ? <Link href={`/pacientes/${task.paciente_id}`} className="inline-flex items-center gap-1 text-primary hover:underline"><UserRound className="h-3.5 w-3.5" />{task.paciente_nome}</Link> : <span className="text-muted-foreground">—</span>}</div><div className="px-4 py-4 align-top"><Badge tone={status.tone}>{status.label}</Badge></div><div className="px-4 py-4 align-top"><TaskActions task={task} assignees={assignees} canEdit={canEdit} /></div></div><article className="border-b border-border p-4 last:border-b-0 md:hidden"><div className="flex items-start justify-between gap-3"><TaskTitle task={task} /><Badge tone={status.tone}>{status.label}</Badge></div><dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 text-xs"><div><dt className="text-muted-foreground">Responsável</dt><dd className="mt-0.5 text-foreground">{task.responsavel_nome}</dd></div><div><dt className="text-muted-foreground">Prazo</dt><dd className="mt-0.5 text-foreground">{task.prazo ? formatClinicDate(task.prazo, { day: "2-digit", month: "short" }) : "Sem prazo"}</dd></div>{task.paciente_id && task.paciente_nome && <div className="col-span-2"><dt className="text-muted-foreground">Paciente</dt><dd className="mt-0.5"><Link href={`/pacientes/${task.paciente_id}`} className="text-primary hover:underline">{task.paciente_nome}</Link></dd></div>}</dl><div className="mt-4"><TaskActions task={task} assignees={assignees} canEdit={canEdit} /></div></article></div>; })}</>;
}

export function TaskPanel({ tasks, assignees, currentUserId, profile }: { tasks: OperationalTask[]; assignees: Assignee[]; currentUserId: string; profile: string }) {
  const pending = tasks.filter((task) => task.status === "pendente").length;
  const completed = tasks.filter((task) => task.status === "concluida").length;
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-medium text-foreground">Tarefas</h2><p className="mt-1 text-sm text-muted-foreground">{pending} {pending === 1 ? "tarefa pendente" : "tarefas pendentes"}</p></div><details className="relative rounded-md bg-primary text-primary-foreground shadow-sm"><summary className="inline-flex h-10 cursor-pointer list-none items-center gap-2 px-4 text-sm font-medium hover:bg-primary/90"><Plus className="h-4 w-4" /> Nova tarefa</summary><div className="absolute right-0 z-30 mt-2 w-[min(44rem,calc(100vw-2rem))] rounded-lg border border-border bg-card text-foreground shadow-xl"><TaskCreationForm assignees={assignees} currentUserId={currentUserId} /></div></details></div><section className="grid gap-3 sm:grid-cols-3" aria-label="Resumo de tarefas"><SummaryCard label="Pendentes" value={pending} description="Aguardam conclusão" icon={CircleDashed} /><SummaryCard label="Em andamento" value="—" description="Status não previsto no modelo" icon={ClipboardCheck} tone="text-muted-foreground" /><SummaryCard label="Concluídas" value={completed} description="Finalizadas" icon={CheckCircle2} tone="text-emerald-600" /></section><section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><h3 className="font-medium text-foreground">Lista de tarefas</h3><p className="mt-0.5 text-xs text-muted-foreground">Prioridade não está cadastrada no modelo atual.</p></div><span className="text-xs text-muted-foreground">{tasks.length} no total</span></div>{tasks.length === 0 ? <div className="px-6 py-12 text-center"><XCircle className="mx-auto h-7 w-7 text-muted-foreground/60" /><p className="mt-3 text-sm font-medium text-foreground">Nenhuma tarefa visível</p><p className="mt-1 text-xs text-muted-foreground">Use “Nova tarefa” para registrar uma pendência operacional.</p></div> : <><div className="hidden overflow-x-auto md:block"><div className="min-w-[54rem]"><div className="table w-full table-fixed border-collapse"><div className="table-header-group bg-secondary/50 text-left text-xs font-medium uppercase tracking-wide text-muted-foreground"><div className="table-row"><div className="table-cell w-[28%] px-4 py-3">Tarefa</div><div className="table-cell w-[15%] px-4 py-3">Responsável</div><div className="table-cell w-[13%] px-4 py-3">Prazo</div><div className="table-cell w-[16%] px-4 py-3">Paciente</div><div className="table-cell w-[12%] px-4 py-3">Status</div><div className="table-cell w-[16%] px-4 py-3">Ações</div></div></div><div className="table-row-group"><TaskRows tasks={tasks} assignees={assignees} currentUserId={currentUserId} profile={profile} /></div></div></div></div><div className="md:hidden"><TaskRows tasks={tasks} assignees={assignees} currentUserId={currentUserId} profile={profile} /></div></>}</section></div>;
}
