import Link from "next/link";
import { Plus } from "lucide-react";
import { requireUser } from "@/lib/auth/session";
import { listServices } from "@/lib/services/queries";
import { isServiceStatus } from "@/lib/services/validation";
import type { ServiceStatus } from "@/lib/services/types";

type SearchParams = Promise<{ q?: string | string[]; status?: string | string[]; page?: string | string[] }>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const statusLabel: Record<ServiceStatus, string> = { ativo: "Ativos", inativo: "Inativos", todos: "Todos" };

export default async function ServicesPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser(); if (user.perfil !== "administrador") return <div className="rounded-xl border border-border bg-card p-6 text-sm">Acesso ao catálogo restrito ao administrador.</div>;
  const params = await searchParams; const query = (first(params.q) ?? "").trim().slice(0, 100); const rawStatus = first(params.status); const status = rawStatus && isServiceStatus(rawStatus) ? rawStatus : "ativo"; const page = Math.max(1, Number(first(params.page) ?? "1") || 1);
  const { services, total, pageSize } = await listServices({ query, status, page }); const pages = Math.max(1, Math.ceil(total / pageSize));
  const href = (next: number) => `/servicos?q=${encodeURIComponent(query)}&status=${status}&page=${next}`;
  return <div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-medium">Serviços</h2><p className="mt-1 text-sm text-muted-foreground">Catálogo, valores padrão e materiais consumidos.</p></div><Link href="/servicos/novo" className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><Plus className="h-4 w-4" />Novo serviço</Link></header><form className="grid gap-2 rounded-xl border border-border bg-card p-3 sm:grid-cols-[1fr_auto_auto]"><input name="q" defaultValue={query} placeholder="Buscar serviço" className="h-10 rounded-md border border-border bg-input-background px-3 text-sm" /><select name="status" defaultValue={status} className="h-10 rounded-md border border-border bg-input-background px-3 text-sm">{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="h-10 rounded-md border border-border px-4 text-sm">Filtrar</button></form>{services.length === 0 ? <section className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">Nenhum serviço encontrado.</section> : <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="hidden grid-cols-[1.4fr_1fr_.7fr_.6fr] gap-3 border-b border-border px-4 py-3 text-xs font-medium uppercase text-muted-foreground md:grid"><span>Serviço</span><span>Categoria</span><span>Valor padrão</span><span>Status</span></div><div className="divide-y divide-border">{services.map((service) => <Link key={service.id} href={`/servicos/${service.id}`} className="grid gap-1 px-4 py-4 hover:bg-secondary/50 md:grid-cols-[1.4fr_1fr_.7fr_.6fr] md:items-center md:gap-3"><span className="font-medium">{service.nome}<span className="mt-1 block text-xs font-normal text-muted-foreground">{service.descricao ?? "Sem descrição"}</span></span><span className="text-sm text-muted-foreground">{service.categoria ?? "—"}</span><span className="text-sm">{new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(service.valor_padrao_centavos / 100)}</span><span className="text-sm">{service.ativo ? "Ativo" : "Inativo"}</span></Link>)}</div></section>}{pages > 1 && <nav className="flex justify-between text-sm"><span> Página {page} de {pages}</span><div className="flex gap-2">{page > 1 && <Link href={href(page - 1)}>Anterior</Link>}{page < pages && <Link href={href(page + 1)}>Próxima</Link>}</div></nav>}</div>;
}
