"use client";

import { useActionState } from "react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { initialDomainActionState } from "@/lib/validity/types";
import { adjustLotStock, registerLotEntry, registerLotExit, setLotActive, setLotControl, updateLotMetadata } from "./actions";

function Feedback({ state }: { state: typeof initialDomainActionState }) { return <>{state.error && <p role="alert" className="text-sm text-destructive">{state.error}</p>}{state.success && <p role="status" className="text-sm text-emerald-700">Operação concluída.</p>}</>; }

export function LotControlForm({ materialId, enabled, currentQuantity }: { materialId: string; enabled: boolean; currentQuantity: number }) {
  const [state, action, pending] = useActionState(setLotControl, initialDomainActionState);
  return <form action={action} className="space-y-3 rounded-xl border border-border bg-card p-4"><input type="hidden" name="materialId" value={materialId}/><input type="hidden" name="enabled" value={String(!enabled)}/><div><h3 className="font-medium">Controle por lote</h3><p className="mt-1 text-xs text-muted-foreground">{enabled ? "Cada entrada e saída exige um lote." : "Ative para rastrear validade e saldo físico por lote."}</p></div>{!enabled && currentQuantity > 0 && <div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-medium">Lote inicial<Input name="codigoLote" required maxLength={100}/></label><label className="text-sm font-medium">Validade<Input name="validade" type="date" required/></label><label className="text-sm font-medium">Fabricação <span className="font-normal text-muted-foreground">(opcional)</span><Input name="fabricacao" type="date"/></label><label className="text-sm font-medium">Fornecedor <span className="font-normal text-muted-foreground">(opcional)</span><Input name="fornecedor" maxLength={200}/></label></div>}<Feedback state={state}/><Button size="sm" variant={enabled ? "secondary" : "primary"} disabled={pending}>{pending ? "Salvando..." : enabled ? "Desativar controle" : "Ativar controle por lote"}</Button></form>;
}

export function LotEntryForm({ materials }: { materials: Array<{ id: string; nome: string }> }) {
  const [state, action, pending] = useActionState(registerLotEntry, initialDomainActionState);
  return <form action={action} className="space-y-4 rounded-xl border border-border bg-card p-5"><h3 className="font-medium">Registrar entrada por lote</h3><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-medium">Material<select name="materialId" required className="mt-1 h-10 w-full rounded-md border border-border bg-input-background px-3 text-sm"><option value="">Selecione</option>{materials.map(item=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label className="text-sm font-medium">Código do lote<Input name="codigoLote" required maxLength={100}/></label><label className="text-sm font-medium">Quantidade<Input name="quantidade" type="number" min="1" max="1000000" required/></label><label className="text-sm font-medium">Validade<Input name="validade" type="date" required/></label><label className="text-sm font-medium">Fabricação <span className="font-normal text-muted-foreground">(opcional)</span><Input name="fabricacao" type="date"/></label><label className="text-sm font-medium">Fornecedor <span className="font-normal text-muted-foreground">(opcional)</span><Input name="fornecedor" maxLength={200}/></label><label className="text-sm font-medium">Motivo <span className="font-normal text-muted-foreground">(opcional)</span><Input name="motivo" maxLength={500}/></label><label className="text-sm font-medium">Referência <span className="font-normal text-muted-foreground">(opcional)</span><Input name="referencia" maxLength={120}/></label></div><Feedback state={state}/><Button disabled={pending}>{pending ? "Registrando..." : "Registrar entrada"}</Button></form>;
}

export function LotExitForm({ materialId, lotId }: { materialId: string; lotId: string }) {
  const [state, action, pending] = useActionState(registerLotExit, initialDomainActionState);
  return <form action={action} className="space-y-3 rounded-xl border border-border bg-card p-4"><input type="hidden" name="materialId" value={materialId}/><input type="hidden" name="lotId" value={lotId}/><h3 className="font-medium">Registrar saída</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Quantidade<Input name="quantidade" type="number" min="1" max="1000000" required/></label><label className="text-sm font-medium">Finalidade<select name="finalidade" required className="mt-1 h-10 w-full rounded-md border border-border bg-input-background px-3 text-sm"><option value="uso">Uso operacional</option><option value="descarte">Descarte</option><option value="perda">Perda</option></select></label><label className="text-sm font-medium">Motivo<Input name="motivo" maxLength={500}/></label><label className="text-sm font-medium">Referência<Input name="referencia" maxLength={120}/></label></div><Feedback state={state}/><Button size="sm" disabled={pending}>{pending ? "Registrando..." : "Registrar saída"}</Button></form>;
}

export function LotActiveForm({ lotId, active }: { lotId: string; active: boolean }) {
  const [state, action, pending] = useActionState(setLotActive, initialDomainActionState);
  return <form action={action} className="flex flex-wrap items-center gap-2"><input type="hidden" name="lotId" value={lotId}/><input type="hidden" name="active" value={String(!active)}/><Button size="sm" variant="secondary" disabled={pending}>{active ? "Inativar lote" : "Reativar lote"}</Button>{state.error && <span role="alert" className="text-xs text-destructive">{state.error}</span>}</form>;
}

export function LotMetadataForm({ lot }: { lot: { id: string; codigo_lote: string; data_validade: string; data_fabricacao: string | null; fornecedor: string | null } }) {
  const [state, action, pending] = useActionState(updateLotMetadata, initialDomainActionState);
  return <form action={action} className="space-y-3 rounded-xl border border-border bg-card p-4"><input type="hidden" name="lotId" value={lot.id} /><h3 className="font-medium">Corrigir dados do lote</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Código<Input name="codigoLote" defaultValue={lot.codigo_lote} required maxLength={100} /></label><label className="text-sm font-medium">Validade<Input name="validade" type="date" defaultValue={lot.data_validade} required /></label><label className="text-sm font-medium">Fabricação<Input name="fabricacao" type="date" defaultValue={lot.data_fabricacao ?? ""} /></label><label className="text-sm font-medium">Fornecedor<Input name="fornecedor" defaultValue={lot.fornecedor ?? ""} maxLength={200} /></label></div><Feedback state={state} /><Button size="sm" disabled={pending}>{pending ? "Salvando..." : "Salvar correção"}</Button></form>;
}

export function LotAdjustmentForm({ lotId, materialId, currentQuantity }: { lotId: string; materialId: string; currentQuantity: number }) {
  const [state, action, pending] = useActionState(adjustLotStock, initialDomainActionState);
  return <form action={action} className="space-y-3 rounded-xl border border-border bg-card p-4"><input type="hidden" name="lotId" value={lotId} /><input type="hidden" name="materialId" value={materialId} /><div><h3 className="font-medium">Ajuste administrativo</h3><p className="mt-1 text-xs text-muted-foreground">Substitui a contagem física do lote e sincroniza o saldo agregado.</p></div><label className="block text-sm font-medium">Nova contagem<Input name="quantidade" type="number" min="0" max="1000000" defaultValue={currentQuantity} required /></label><label className="block text-sm font-medium">Motivo<textarea name="motivo" required minLength={2} maxLength={500} rows={2} className="mt-1 w-full rounded-md border border-border bg-input-background p-2 text-sm" /></label><label className="block text-sm font-medium">Referência <span className="font-normal text-muted-foreground">(opcional)</span><Input name="referencia" maxLength={120} /></label><Feedback state={state} /><Button size="sm" disabled={pending}>{pending ? "Ajustando..." : "Registrar ajuste"}</Button></form>;
}
