"use client";

import { useMemo, useState } from "react";
import { useActionState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { PatientPicker } from "@/app/(app)/agenda/PatientPicker";
import { formatCents } from "@/lib/budgets/validation";
import { initialBudgetActionState, type BudgetDetail } from "@/lib/budgets/types";
import { saveBudget } from "./actions";

type DraftItem = { id?: string; descricao: string; quantidade: number; valorUnitarioCentavos: number; removed?: boolean };
const newItem = (): DraftItem => ({ descricao: "", quantidade: 1, valorUnitarioCentavos: 0 });

export function BudgetEditor({ budget, patient, professionals }: { budget?: BudgetDetail; patient?: { id: string; nome: string; telefone_contato: string | null } | null; professionals: { id: string; nome: string }[] }) {
  const [items, setItems] = useState<DraftItem[]>(budget?.items.map((item) => ({ id: item.id, descricao: item.descricao, quantidade: item.quantidade, valorUnitarioCentavos: item.valor_unitario_centavos })) ?? [newItem()]);
  const [state, action, pending] = useActionState(saveBudget, initialBudgetActionState);
  const total = useMemo(() => items.filter((item) => !item.removed).reduce((sum, item) => sum + Math.max(0, item.quantidade || 0) * Math.max(0, item.valorUnitarioCentavos || 0), 0), [items]);
  const editable = !budget || budget.effective_status === "rascunho";
  const update = (index: number, field: keyof DraftItem, value: string | number | boolean) => setItems((current) => current.map((item, position) => position === index ? { ...item, [field]: value } : item));
  return <form action={action} className="space-y-5"><input type="hidden" name="budgetId" value={budget?.id ?? ""}/><input type="hidden" name="items" value={JSON.stringify(items)}/>
    <section className="rounded-lg border bg-card p-5"><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2">{patient ? <><input type="hidden" name="patientId" value={patient.id}/><div className="rounded-md bg-secondary px-3 py-2 text-sm"><span className="text-muted-foreground">Paciente: </span><span className="font-medium">{patient.nome}</span></div></> : <PatientPicker searchLabel="Buscar paciente para orçamento" error={state.fieldErrors?.patientId}/>}</div><label className="text-sm">Profissional responsável<select name="professionalId" required disabled={!editable} defaultValue={budget?.profissional_id ?? ""} className="mt-1 block h-10 w-full rounded border bg-background px-3 disabled:opacity-60"><option value="">Selecione</option>{professionals.map((professional) => <option key={professional.id} value={professional.id}>{professional.nome}</option>)}</select></label><label className="text-sm">Validade{editable && <span className="text-muted-foreground"> (obrigatória ao enviar)</span>}<input name="validity" type="date" disabled={!editable} defaultValue={budget?.validade_em ?? ""} className="mt-1 block h-10 w-full rounded border bg-background px-3 disabled:opacity-60"/>{state.fieldErrors?.validity && <span className="mt-1 block text-xs text-destructive">{state.fieldErrors.validity}</span>}</label><label className="text-sm md:col-span-2">Observação administrativa<textarea name="observation" maxLength={1000} disabled={!editable} defaultValue={budget?.observacao_administrativa ?? ""} className="mt-1 block min-h-24 w-full rounded border bg-background p-3 text-sm disabled:opacity-60"/></label></div></section>
    <section className="rounded-lg border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-medium">Itens</h3><p className="mt-1 text-xs text-muted-foreground">Valores em reais; o sistema grava os valores em centavos.</p></div>{editable && <button type="button" onClick={() => setItems((current) => [...current, newItem()])} className="inline-flex h-9 items-center gap-1 rounded border px-3 text-sm hover:bg-secondary"><Plus className="h-4 w-4"/>Adicionar item</button>}</div><div className="mt-4 space-y-3">{items.map((item, index) => item.removed ? null : <div key={item.id ?? `new-${index}`} className="grid gap-2 rounded-md border p-3 md:grid-cols-[minmax(0,1fr)_6rem_9rem_auto]"><input aria-label={`Descrição do item ${index + 1}`} disabled={!editable} value={item.descricao} maxLength={300} onChange={(event) => update(index, "descricao", event.target.value)} placeholder="Descrição" className="h-10 rounded border bg-background px-3 text-sm disabled:opacity-60"/><input aria-label={`Quantidade do item ${index + 1}`} disabled={!editable} value={item.quantidade} min="1" max="999" type="number" onChange={(event) => update(index, "quantidade", Number(event.target.value))} className="h-10 rounded border bg-background px-3 text-sm disabled:opacity-60"/><input aria-label={`Valor unitário do item ${index + 1}`} disabled={!editable} value={(item.valorUnitarioCentavos / 100).toFixed(2)} min="0" step="0.01" type="number" onChange={(event) => update(index, "valorUnitarioCentavos", Math.round(Number(event.target.value) * 100))} className="h-10 rounded border bg-background px-3 text-sm disabled:opacity-60"/>{editable && <button type="button" aria-label="Remover item" onClick={() => update(index, "removed", true)} className="inline-flex h-10 w-10 items-center justify-center rounded border text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button>}</div>)}</div><div className="mt-4 flex justify-end border-t pt-4 text-base font-semibold">Total: {formatCents(total)}</div></section>
    {state.error && <p role="alert" className="text-sm text-destructive">{state.error}</p>}{editable && <div className="flex flex-wrap justify-end gap-2"><button type="submit" name="desiredStatus" value="rascunho" disabled={pending} className="h-10 rounded border px-4 text-sm font-medium hover:bg-secondary">Salvar rascunho</button><button type="submit" name="desiredStatus" value="enviado" disabled={pending} className="h-10 rounded bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90">{pending ? "Salvando..." : "Salvar e enviar"}</button></div>}</form>;
}
