"use client";
import { useActionState } from "react";
import { initialServiceActionState, type ServiceMaterial } from "@/lib/services/types";
import { configureServiceMaterial, setServiceMaterialActive } from "../actions";

export function ServiceMaterials({ serviceId, materials, stockMaterials }: { serviceId: string; materials: ServiceMaterial[]; stockMaterials: Array<{ id: string; nome: string }> }) {
  const [addState, addAction, adding] = useActionState(configureServiceMaterial, initialServiceActionState);
  const [toggleState, toggleAction, toggling] = useActionState(setServiceMaterialActive, initialServiceActionState);
  return <section className="rounded-xl border border-border bg-card p-5"><div><h3 className="font-medium">Materiais consumidos</h3><p className="mt-1 text-xs text-muted-foreground">A composição vale para novos serviços registrados; não movimenta estoque agora.</p></div><div className="mt-4 divide-y divide-border rounded-lg border border-border">{materials.length === 0 ? <p className="p-4 text-sm text-muted-foreground">Nenhum material configurado.</p> : materials.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-3 text-sm"><span>{item.material_nome} · {item.quantidade_padrao}</span><form action={toggleAction}><input type="hidden" name="serviceId" value={serviceId} /><input type="hidden" name="serviceMaterialId" value={item.id} /><input type="hidden" name="ativo" value={item.ativo ? "false" : "true"} /><button disabled={toggling} className="text-primary">{item.ativo ? "Desativar" : "Reativar"}</button></form></div>)}</div><form action={addAction} className="mt-4 grid gap-2 sm:grid-cols-[1fr_8rem_auto]"><input type="hidden" name="serviceId" value={serviceId} /><select name="materialId" required className="h-10 rounded-md border border-border bg-input-background px-3 text-sm"><option value="">Selecionar material ativo</option>{stockMaterials.map((material) => <option key={material.id} value={material.id}>{material.nome}</option>)}</select><input name="quantidade" type="number" min="1" max="1000000" required defaultValue="1" className="h-10 rounded-md border border-border px-3 text-sm" /><button disabled={adding} className="h-10 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">{adding ? "Salvando..." : "Adicionar"}</button>{(addState.error || toggleState.error) && <p role="alert" className="sm:col-span-3 text-sm text-destructive">{addState.error ?? toggleState.error}</p>}</form></section>;
}
